image: node:8.11.1
pages:
  cache:
    paths:
      - node_modules/
  before_script:
    - npm install hexo-cli
  script:
    - hexo -v
    - npm install
    - hexo deploy
  artifacts:
    paths:
      - public
  only:
    - master