image: node:4.5.0
pages:
  cache:
    paths:
    - node_modules/
  script:
  - npm install hexo-cli -g
  - npm install
  - hexo deploy
  artifacts:
    paths:
    - public
  only:
  - master
tls:
  script:
    - npm install -g gitlab-letsencrypt-hexo
    - gitlab-le-hexo --email ycrxun@163.com --domain ronggle.com --repository ycrxun/ycrxun.gitlab.io --token $TOKEN